import com.acronym.base.IMaterialType;
/*
    var abyssalnite = mods.base.Materials.getOrRegister("abyssalnite",  1,  1, false);
    var adamantine = mods.base.Materials.getOrRegister("adamantine",  1,  1, false);
    var aluminum = mods.base.Materials.getOrRegister("aluminum",  1,  1, false);
    var aquarium = mods.base.Materials.getOrRegister("aquarium",  1,  1, false);
    var ardite = mods.base.Materials.getOrRegister("ardite",  1,  1, false);
    var brass = mods.base.Materials.getOrRegister("brass",  1,  1, false);
    var bronze = mods.base.Materials.getOrRegister("bronze",  1,  1, false);
    var cobalt = mods.base.Materials.getOrRegister("cobalt",  1,  1, false);
    var coldiron = mods.base.Materials.getOrRegister("cold-iron",  1,  1, false);
    var copper = mods.base.Materials.getOrRegister("copper",  1,  13137203, false);
    var coralium = mods.base.Materials.getOrRegister("coralium",  1,  1, false);
    var cupronickel = mods.base.Materials.getOrRegister("cupronickel",  1,  1, false);
    var dilithium = mods.base.Materials.getOrRegister("dilithium",  1,  1, false);
    var dreadium = mods.base.Materials.getOrRegister("dreadium",  1,  1, false);
    var electrum = mods.base.Materials.getOrRegister("electrum",  1,  1, false);
    var gold = mods.base.Materials.getOrRegister("gold",  1,  1, false);
    var invar = mods.base.Materials.getOrRegister("invar",  1,  1, false);
    var iridium = mods.base.Materials.getOrRegister("iridium",  1,  1, false);
    var iron = mods.base.Materials.getOrRegister("iron",  1,  1, false);
    var lead = mods.base.Materials.getOrRegister("lead",  1,  1, false);
    var mithril = mods.base.Materials.getOrRegister("mithril",  1,  1, false);
    var nickel = mods.base.Materials.getOrRegister("nickel",  1,  1, false);
    var platinum = mods.base.Materials.getOrRegister("platinum",  1,  1, false);
    var silver = mods.base.Materials.getOrRegister("silver",  1,  1, false);
    var starsteel = mods.base.Materials.getOrRegister("starsteel",  1,  1, false);
    var steel = mods.base.Materials.getOrRegister("steel",  1,  1, false);
    var tin = mods.base.Materials.getOrRegister("tin",  1,  1, false);
    var titanium = mods.base.Materials.getOrRegister("titanium",  1,  1, false);
    var uranium = mods.base.Materials.getOrRegister("uranium",  1,  1, false);
    var zinc = mods.base.Materials.getOrRegister("zinc",  1,  1, false);
*/
