# This script is to make nether ores equal to overworld ores (just with a different texture).

furnace.remove(<*>, <nethermetals:nether_emerald_ore>);
furnace.remove(<*>, <nethermetals:nether_diamond_ore>);
furnace.remove(<*>, <nethermetals:nether_coal_ore>);
furnace.remove(<*>, <nethermetals:nether_gold_ore>);
furnace.remove(<*>, <nethermetals:nether_iron_ore>);
furnace.remove(<*>, <nethermetals:nether_lapis_ore>);
furnace.remove(<*>, <nethermetals:nether_redstone_ore>);
furnace.remove(<*>, <nethermetals:nether_antimony_ore>);
furnace.remove(<*>, <nethermetals:nether_bismuth_ore>);
furnace.remove(<*>, <nethermetals:nether_copper_ore>);
furnace.remove(<*>, <nethermetals:nether_lead_ore>);
furnace.remove(<*>, <nethermetals:nether_mercury_ore>);
furnace.remove(<*>, <nethermetals:nether_nickel_ore>);
furnace.remove(<*>, <nethermetals:nether_platinum_ore>);
furnace.remove(<*>, <nethermetals:nether_silver_ore>);
furnace.remove(<*>, <nethermetals:nether_tin_ore>);
furnace.remove(<*>, <nethermetals:nether_zinc_ore>);
furnace.remove(<*>, <nethermetals:nether_aluminum_ore>);
furnace.remove(<*>, <nethermetals:nether_cadmium_ore>);
furnace.remove(<*>, <nethermetals:nether_chromium_ore>);
furnace.remove(<*>, <nethermetals:nether_iridium_ore>);
furnace.remove(<*>, <nethermetals:nether_magnesium_ore>);
furnace.remove(<*>, <nethermetals:nether_manganese_ore>);
furnace.remove(<*>, <nethermetals:nether_osmium_ore>);
furnace.remove(<*>, <nethermetals:nether_plutonium_ore>);
furnace.remove(<*>, <nethermetals:nether_rutile_ore>);
furnace.remove(<*>, <nethermetals:nether_tantalum_ore>);
furnace.remove(<*>, <nethermetals:nether_titanium_ore>);
furnace.remove(<*>, <nethermetals:nether_tungsten_ore>);
furnace.remove(<*>, <nethermetals:nether_uranium_ore>);
furnace.remove(<*>, <nethermetals:nether_zirconium_ore>);

furnace.remove(<*>, <nethercore:ore:0>);
furnace.remove(<*>, <nethercore:ore:1>);
furnace.remove(<*>, <nethercore:ore:2>);
furnace.remove(<*>, <nethercore:ore:3>);
furnace.remove(<*>, <nethercore:ore:4>);
furnace.remove(<*>, <nethercore:ore:5>);
furnace.remove(<*>, <nethercore:ore:6>);


<ore:oreEmerald>.add(<nethermetals:nether_emerald_ore>);
<ore:oreDiamond>.add(<nethermetals:nether_diamond_ore>);
<ore:oreCoal>.add(<nethermetals:nether_coal_ore>);
<ore:oreGold>.add(<nethermetals:nether_gold_ore>);
<ore:oreIron>.add(<nethermetals:nether_iron_ore>);
<ore:oreLapis>.add(<nethermetals:nether_lapis_ore>);
<ore:oreRedstone>.add(<nethermetals:nether_redstone_ore>);
<ore:oreAntimony>.add(<nethermetals:nether_antimony_ore>);
<ore:oreBismuth>.add(<nethermetals:nether_bismuth_ore>);
<ore:oreCopper>.add(<nethermetals:nether_copper_ore>);
<ore:oreLead>.add(<nethermetals:nether_lead_ore>);
<ore:oreMercury>.add(<nethermetals:nether_mercury_ore>);
<ore:oreNickel>.add(<nethermetals:nether_nickel_ore>);
<ore:orePlatinum>.add(<nethermetals:nether_platinum_ore>);
<ore:oreSilver>.add(<nethermetals:nether_silver_ore>);
<ore:oreTin>.add(<nethermetals:nether_tin_ore>);
<ore:oreZinc>.add(<nethermetals:nether_zinc_ore>);
<ore:oreAluminum>.add(<nethermetals:nether_aluminum_ore>);
<ore:oreCadmium>.add(<nethermetals:nether_cadmium_ore>);
<ore:oreChromium>.add(<nethermetals:nether_chromium_ore>);
<ore:oreIridium>.add(<nethermetals:nether_iridium_ore>);
<ore:oreMagnesium>.add(<nethermetals:nether_magnesium_ore>);
<ore:oreManganese>.add(<nethermetals:nether_manganese_ore>);
<ore:oreOsmium>.add(<nethermetals:nether_osmium_ore>);
<ore:orePlutonium>.add(<nethermetals:nether_plutonium_ore>);
<ore:oreRutile>.add(<nethermetals:nether_rutile_ore>);
<ore:oreTantalum>.add(<nethermetals:nether_tantalum_ore>);
<ore:oreTitanium>.add(<nethermetals:nether_titanium_ore>);
<ore:oreTungsten>.add(<nethermetals:nether_tungsten_ore>);
<ore:oreUranium>.add(<nethermetals:nether_uranium_ore>);
<ore:oreZirconium>.add(<nethermetals:nether_zirconium_ore>);

<ore:oreCoal>.add(<nethercore:ore:0>);
<ore:oreIron>.add(<nethercore:ore:1>);
<ore:oreGold>.add(<nethercore:ore:2>);
<ore:oreRedstone>.add(<nethercore:ore:3>);
<ore:oreLapis>.add(<nethercore:ore:4>);
<ore:oreDiamond>.add(<nethercore:ore:5>);
<ore:oreEmerald>.add(<nethercore:ore:6>);

